### ISSUE TITLE
Research open source projects to fork and build upon

### ISSUE THREAD

**Issue by Mostafa-wael** [tactful-ai/OPA#1]
As per Maram's suggestion, we need to rethink our approach by looking for an open source project similar to ours and trying to start our implementation from there

**Comment by AhmadJamal01** [comment]
Nada has already suggested OPAL, but finding and understanding an open source codebase can be quite difficult. Assuming an optimistic estimate of 12 hours, a pessimistic estimate of 30 hours, and a most likely estimate of 20 hours,

ß = (12+30+20*4)/6 = 20.3 hours

**Comment by AhmadJamal01** [comment]
Up till now the decision we have reached is to build upon OPAL to help us speed up the process. We still await confirmation from Mostafa and Maram if OPAL is acceptable to use.

**Comment by Mostafa-wael** [comment]
You are allowed to use it as you want.
